// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PhotoFinder.Entity;

public partial class Booking
{
    public int BookingId { get; set; }

    public int CustomerId { get; set; }

    public int PhotographerId { get; set; }

    public DateTime EventDate { get; set; }

    public string EventLocation { get; set; }

    public string Status { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Photographer Photographer { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}