// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PhotoFinder.Entity;

public partial class Package
{
    public int PackageId { get; set; }

    public int PhotographerId { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Duration { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }
}