// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PhotoFinder.Entity;

public partial class Photographer
{
    public int PhotographerId { get; set; }

    public int UserId { get; set; }

    public string Bio { get; set; }

    public string PortfolioUrl { get; set; }

    public double? Rating { get; set; }

    public string Location { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Availability> Availabilities { get; set; } = new List<Availability>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    public virtual ICollection<Photo> Photos { get; set; } = new List<Photo>();

    public virtual User User { get; set; }
}