// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PhotoFinder.Entity;

public partial class Photo
{
    public int PhotoId { get; set; }

    public int PhotographerId { get; set; }

    public string PhotoUrl { get; set; }

    public bool? IsPublic { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual Photographer Photographer { get; set; }
}